kind: Namespace
apiVersion: v1
metadata:
  name: ingress
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-orign-ca
  namespace: ingress
spec:
  interval: 24h
  ref:
    branch: trunk
  url: https://github.com/cloudflare/origin-ca-issuer.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-orign-ca-crds
  namespace: ingress
spec:
  interval: 10m0s
  path: deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-orign-ca
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: ingress
spec:
  interval: 10m0s
  path: ./ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: secrets
      namespace: flux-system
    - name: cloudflare-orign-ca-crds
