kind: Namespace
apiVersion: v1
metadata:
  name: kube-prometheus
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: kube-prometheus
spec:
  interval: 10m0s
  path: ./kube-prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
