apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: cloudflare
  namespace: ingress
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cfapi-token
      key: key
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare
  namespace: ingress
spec:
  plugin:
    cloudflare:
      # Cloudflare connects via cloudflared
      trustedCIDRs: ["10.244.0.0/16", "10.32.4.0/22"]
      overwriteRequestHeader: true
