apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: cloudflare
  namespace: ingress
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cfapi-token
      key: key
---
