apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-receivers
  namespace: flux-system
spec:
  parentRefs:
    - name: cloudflare
      namespace: ingress
  hostnames:
    - "flux-receiver.kbs610.click"
  rules:
    - backendRefs:
        - name: webhook-receiver
          namespace: flux-system
          port: 80
