apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-config
  namespace: ingress
spec:
  interval: 10m0s
  path: ./ingress/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: secrets
      namespace: flux-system
    - name: cloudflare-orign-ca-crds
    - name: ingress
